<?php

/**
 * @file
 * Contains informaid_paragraphs.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_help().
 */
function informaid_paragraphs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the informaid_paragraphs module.
    case 'help.page.informaid_paragraphs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Paragraphs for informaid') . '</p>';
      return $output;

    default:
  }
}

/**
 * {@inheritDoc}
 */
function informaid_paragraphs_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  // For nodes, change the view mode when it is teaser.
  if ($entity instanceof Paragraph && $entity->field_view_mode) {
    $pViewMode = $entity->field_view_mode[0]->target_id;
    $view_mode = explode('.', $pViewMode)[1];
  }
}

/**
 * {@inheritDoc}
 */
function informaid_paragraphs_preprocess_paragraph(&$variables) {
  $paragraph = $variables['elements']['#paragraph'];

  if ($variables['view_mode'] === 'background_image') {
    $imageItem = $paragraph->field_media_image[0]->entity->field_media_image[0];
    $uri = $imageItem->entity->uri->value;
    $variables['imageUrl'] = file_create_url($uri);
  }
  if ($paragraph->bundle() === 'title_text') {
    $parent = $paragraph->getParentEntity();
    if ($parent->parent_field_name->value === 'field_header') {
      $variables['nodeTitle'] = $parent->getParentEntity()->getTitle();
    }
  }
}
